# Generated by Django 5.2.17 on 2026-09-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(default='Running', max_length=20)),
                ('plan', models.CharField(default='Basic', max_length=50)),
            ],
        ),
    ]
