# Generated by Django 5.2.17 on 2026-09-12 05:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vps',
            name='billing_cycle',
            field=models.CharField(default='Monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='vps',
            name='cpu',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='vps',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vps',
            name='operating_system',
            field=models.CharField(default='Ubuntu 26.04', max_length=100),
        ),
        migrations.AddField(
            model_name='vps',
            name='ram',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='vps',
            name='storage',
            field=models.IntegerField(default=32),
        ),
        migrations.AddField(
            model_name='vps',
            name='vmid',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vps',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AlterField(
            model_name='vps',
            name='status',
            field=models.CharField(default='Provisioning', max_length=20),
        ),
    ]
