# Generated by Django 5.2.17 on 2026-09-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0004_vps_current_step_vps_order_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='vps',
            name='billing_order_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
