# Generated by Django 5.2.17 on 2026-09-25 03:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0005_vps_billing_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerOperation',
            fields=[
                ('operation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.UUIDField(editable=False, unique=True)),
                ('billing_order_id', models.PositiveBigIntegerField()),
                ('target_vmid', models.PositiveIntegerField()),
                ('target_node', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('start', 'start'), ('shutdown', 'shutdown'), ('reboot', 'reboot')], max_length=8)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('succeeded', 'succeeded'), ('failed', 'failed'), ('unknown', 'unknown')], default='pending', max_length=9)),
                ('result', models.CharField(choices=[('executed', 'executed'), ('noop', 'noop')], default=None, max_length=8, null=True)),
                ('observed_state', models.CharField(choices=[('running', 'running'), ('stopped', 'stopped'), ('paused', 'paused'), ('suspended', 'suspended'), ('unknown', 'unknown')], default='unknown', max_length=9)),
                ('observed_at', models.DateTimeField(null=True)),
                ('task_upid', models.TextField(blank=True, default='')),
                ('error_code', models.CharField(blank=True, default='', max_length=40)),
                ('claimed_at', models.DateTimeField(null=True)),
                ('submission_started_at', models.DateTimeField(null=True)),
                ('poll_claimed_at', models.DateTimeField(null=True)),
                ('next_poll_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vps', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='power_operations', to='vps.vps')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'updated_at'], name='power_work_idx'), models.Index(fields=['status', 'next_poll_at'], name='power_poll_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('pending', 'running', 'unknown'))), fields=('vps',), name='one_unresolved_power_per_vps'), models.CheckConstraint(condition=models.Q(('action__in', ('start', 'shutdown', 'reboot'))), name='power_valid_action'), models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'running', 'succeeded', 'failed', 'unknown'))), name='power_valid_status'), models.CheckConstraint(condition=models.Q(('observed_state__in', ('running', 'stopped', 'paused', 'suspended', 'unknown'))), name='power_valid_state'), models.CheckConstraint(condition=models.Q(models.Q(('result__in', ('executed', 'noop')), ('result__isnull', False), ('status', 'succeeded')), models.Q(models.Q(('status', 'succeeded'), _negated=True), ('result__isnull', True)), _connector='OR'), name='power_result_matches_status')],
            },
        ),
    ]
